require('plugins.lualine')
require('plugins.oil') -- Testing if I can make it useful.
require('plugins.carbon')
require('plugins.leap')
require('plugins.dap')
require('plugins.treesitter')
require('plugins.lspconfig')
require('plugins.clangd')
require('plugins.snippy')
require('plugins.cmp')
require('plugins.gitsigns')
require('plugins.fzf')
